name: CICD

on:
  push:
    branches: [prod]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t figorisk/figorisk-core .
      - name: Publish image to docker hub
        run: docker push figorisk/figorisk-core:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull figorisk/figorisk-core:latest
      - name: Delete old container
        run: sudo docker rm -f figorisk-core-container
      - name: Run docker container
        run: |
          sudo docker run -d -p 3000:3000 --name figorisk-core-container \
            -e MONGO_URI="${{ secrets.MONGO_URI }}" \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            -e SUPER_ADMIN_PASSWORD="${{ secrets.SUPER_ADMIN_PASSWORD }}" \
            -e SMTP_USER="${{ secrets.SMTP_USER }}" \
            -e SMTP_PASS="${{ secrets.SMTP_PASS }}" \
            -e SMTP_HOST="${{ secrets.SMTP_HOST }}" \
            -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -e AWS_S3_REGION="${{ secrets.AWS_S3_REGION }}" \
            -e AWS_S3_BUCKET_NAME="${{ secrets.AWS_S3_BUCKET_NAME }}" \
            figorisk/figorisk-core:latest
