pipeline {
    agent any
    environment {
        DOCKER_COMPOSE_FILE = "docker-compose.yml"
    }
    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }
        stage('Build Services') {
            steps {
                sh 'docker-compose build'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'docker-compose run authentication-service npm test'
                sh 'docker-compose run video-streaming-service npm test'
                sh 'docker-compose run watchlist-service npm test'
            }
        }
        stage('Deploy Services') {
            steps {
                sh 'docker-compose up -d'
            }
        }
    }
    post {
        always {
            echo 'Cleaning up resources...'
            sh 'docker-compose down'
        }
    }
}
