name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Authentication Service Job
  authentication-service:
    name: 🐳 Authentication Service - Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for Authentication Service
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies for Authentication Service
        run: npm install
        working-directory: ./authentication-service

      - name: Build Docker image for Authentication Service
        run: docker build -t authentication-service ./authentication-service

  # Video Streaming Service Job
  video-streaming-service:
    name: 🎥 Video Service - Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for Video Service
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies for Video Service
        run: npm install
        working-directory: ./video-streaming-service

      - name: Build Docker image for Video Service
        run: docker build -t video-streaming-service ./video-streaming-service

  # API Gateway Job
  api-gateway:
    name: 🚪 API Gateway - Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for API Gateway
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies for API Gateway
        run: npm install
        working-directory: ./api-gateway

      - name: Build Docker image for API Gateway
        run: docker build -t api-gateway ./api-gateway
  # Watchlist Service Job
  watchlist-service:
    name: 📺 Watchlist Service - Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for Watchlist Service
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies for Watchlist Service
        run: npm install
        working-directory: ./watchlist-service

      - name: Build Docker image for Watchlist Service
        run: docker build -t watchlist-service ./watchlist-service
